#pragma once

/**
 * CRSF_SYNC
 * https://github.com/crsf-wg/crsf/wiki/CRSF-Addresses
 */
#define CRSF_ADDRESS_BROADCAST 0x00
#define CRSF_ADDRESS_USB 0x10
#define CRSF_ADDRESS_BLUETOOTH 0x12
#define CRSF_ADDRESS_TBS_CORE_PNP_PRO 0x80
#define CRSF_ADDRESS_RESERVED1 0x8A
#define CRSF_ADDRESS_CURRENT_SENSOR 0xC0
#define CRSF_ADDRESS_GPS 0xC2
#define CRSF_ADDRESS_TBS_BLACKBOX 0xC4
#define CRSF_ADDRESS_FLIGHT_CONTROLLER 0xC8
#define CRSF_ADDRESS_RESERVED2 0xCA
#define CRSF_ADDRESS_RACE_TAG 0xCC
#define CRSF_ADDRESS_RADIO_TRANSMITTER 0xEA
#define CRSF_ADDRESS_CRSF_RECEIVER 0xEC
#define CRSF_ADDRESS_CRSF_TRANSMITTER 0xEE
#define CRSF_ADDRESS_ELRS_LUA 0xEF

/**
 * CRSF_LEN
 */
#define CRSF_PAYLOAD_MAX_LEN 60
#define CRSF_LEN (CRSF_PAYLOAD_MAX_LEN + 2)
#define CRSF_PKT_LEN (CRSF_PAYLOAD_MAX_LEN + 4)

/**
 * CRSF_TYPE (Unrealized)
 * https://github.com/crsf-wg/crsf/wiki/Packet-Types
 */
#define CRSF_FRAMETYPE_DEVICE_PING 0x28
#define CRSF_FRAMETYPE_DEVICE_INFO 0x29
#define CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY 0x2B
#define CRSF_FRAMETYPE_PARAMETER_READ 0x2C
#define CRSF_FRAMETYPE_PARAMETER_WRITE 0x2D
#define CRSF_FRAMETYPE_ELRS_STATUS 0x2E
#define CRSF_FRAMETYPE_COMMAND 0x32
#define CRSF_FRAMETYPE_RADIO_ID 0x3A
#define CRSF_FRAMETYPE_KISS_REQ 0x78
#define CRSF_FRAMETYPE_KISS_RESP 0x79
#define CRSF_FRAMETYPE_MSP_REQ 0x7A
#define CRSF_FRAMETYPE_MSP_RESP 0x7B
#define CRSF_FRAMETYPE_MSP_WRITE 0x7C
#define CRSF_FRAMETYPE_DISPLAYPORT_CMD 0x7D
#define CRSF_FRAMETYPE_ARDUPILOT_RESP 0x80

/**
 * CRC
 */
// #define POLY 0xD5
