/**
 * https://github.com/ExpressLRS/ExpressLRS/wiki/CRSF-Protocol/aab6bdf4b6828cbb2512755b82f23d1d9e55b854
 */
#pragma once

#define CRSF_ADDRESS_FLIGHT_CONTROLLER 0xC8
#define CRSF_ADDRESS_RADIO_TRANSMITTER 0xEA
#define CRSF_ADDRESS_CRSF_RECEIVER 0xEC
#define CRSF_ADDRESS_CRSF_TRANSMITTER 0xEE
#define CRSF_ADDRESS_ELRS_LUA 0xEF

/**
 * CRSF_LEN
 */
#define CRSF_PAYLOAD_MAX_LEN 60
#define CRSF_LEN (CRSF_PAYLOAD_MAX_LEN + 2)
#define CRSF_PKT_LEN (CRSF_PAYLOAD_MAX_LEN + 4)

/**
 * CRSF_TYPE
 * ---
 * CRSF_FRAMETYPE_LINK_STATISTICS = 0x14
 * CRSF_FRAMETYPE_RC_CHANNELS_PACKED = 0x16
 * CRSF_FRAMETYPE_DEVICE_PING = 0x28
 * CRSF_FRAMETYPE_DEVICE_INFO = 0x29
 * CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY = 0x2B
 * CRSF_FRAMETYPE_PARAMETER_READ = 0x2C
 * CRSF_FRAMETYPE_PARAMETER_WRITE = 0x2D
 * CRSF_FRAMETYPE_COMMAND = 0x32
 */

// #define POLY 0xD5
